name: SnowBomber workflow
on: [push]
jobs:
  build_and_push_dockerhub:
    name: Push images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push web app to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/Dockerfile
          tags: fsow/snowbomber:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_dockerhub
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Copy files from repository to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD}}
          source: docker/docker-compose.yaml, docker/nginx/nginx.conf
          target: ~/
      - name: execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          DB_ENGINE: ${{ secrets.DB_ENGINE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          DJANGO_KEY: ${{ secrets.DJANGO_KEY }}
          TOR_PASSWORD: ${{ secrets.TOR_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD}}
          envs: DB_ENGINE,DB_HOST,DB_PORT,POSTGRES_DB,POSTGRES_PASSWORD,POSTGRES_USER,TELEGRAM_TOKEN,SERVER_PASSWORD,DJANGO_KEY,TOR_PASSWORD
          script: |
            echo DB_ENGINE=$DB_ENGINE > ~/docker/.env && echo DB_HOST=$DB_HOST >> ~/docker/.env && \
            echo DB_PORT=$DB_PORT >> ~/docker/.env && echo POSTGRES_DB=$POSTGRES_DB >> ~/docker/.env && \
            echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> ~/docker/.env && \
            echo POSTGRES_USER=$POSTGRES_USER >> ~/docker/.env && echo TELEGRAM_TOKEN=$TELEGRAM_TOKEN >> ~/docker/.env && \
            echo DJANGO_KEY=$DJANGO_KEY >> ~/docker/.env && echo TOR_PASSWORD=$TOR_PASSWORD >> ~/docker/.env
            cd docker && echo $SERVER_PASSWORD | sudo -S docker-compose pull && \
            echo $SERVER_PASSWORD | sudo -S docker-compose up -d
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Event ${{ github.event_name}} on ${{ github.workflow }} successfully!